blank_issues_enabled: false
contact_links:
  - name: Support question
    url: https://github.com/nuwave/lighthouse/discussions/new?category=q-a
    about: Use GitHub discussions to ask and answer support questions
